### ISSUE TITLE
Changing menu organisation covers up buttons from some other mods

### ISSUE THREAD

**Issue by kianzarrin** [keallu/CSL-ResizeIt#1]
![image](https://user-images.githubusercontent.com/26344691/81769026-3670b880-94e5-11ea-837d-194b634bb78c.png)

The following mods put their buttons under the road selection panel:
Crossing 
Roundabout builder
Pedestrian bridge builder
grid
zoning toggle
...

All these buttons will be hidden when resize it moves the road button under the road options panel. only when choosing transport road those buttons can appear on the top of the CS buttons as shown in the screenshot.

why do you move the buttons over there anyway?

**Comment by keallu** [comment]
When I originally made the mod a lot of these mods didn't exist or added buttons so it wasn't a problem at that time. I will add it to my todo list and possible make a fix or workaround. With the new UnifiedUI I guess the problem is less urgent, since more and more mods are added to this instead of having buttons all over the interface.
